meta_product_name: "AFTERWAY"
meta_title: "AFTERWAY - Leads the way"
meta_description: "Present to the people a list a of bar according to their taste and not too far from the working place and the home of everybody"
meta_image: "banner_afterway.png"
twitter_account: "@product_twitter_account"
